# Cop call,  U. Klank klank@in.tum.de
# Message to query cop
uint64 LOCATE = 0
uint64 TRACK  = 16
uint64 REFINE  = 256
uint64 STOPTRACK = 2048
uint64 STARTATTENT = 4096
uint64 STOPATTENT = 8192
uint64 LOOKUP = 25600
uint64 LOOKUPALL = 25601

string outputtopic           #name of the topic where the answer should be published
string[] object_classes      #descriptor/object class name
uint64[] object_ids          #id of an previously seen object
uint64 action_type           #actiontype: e.g. LOCATE, REFINE or STARTATTENT
uint64 number_of_objects     #number of objects
vision_msgs/apriori_position[] list_of_poses 	   #pose matrix, fully projective 4x4 matrix
---
uint64 perception_primitive  # return a unique id for the called perception primitive which has to be used for later feedback with cop_feedback